let outputStr = "";
test(`Writes a program that uses console.log to print all the numbers from 1 to 100, with two exceptions. 
For numbers divisible by 3, print "Fizz" instead of the number, and for numbers divisible by 5 (and not 3) print "Buzz" instead.
For numbers that are divisible by both 3 and 5, print "FizzBuzz`, () => {
    console["log"] = jest.fn(str => outputStr += `${str}\n`);
    require('../2.fizzbuzz.js');
    expect(outputStr).toBe(
        '1\n' +
        '2\n' +
        'Fizz\n' +
        '4\n' +
        'Buzz\n' +
        'Fizz\n' +
        '7\n' +
        '8\n' +
        'Fizz\n' +
        'Buzz\n' +
        '11\n' +
        'Fizz\n' +
        '13\n' +
        '14\n' +
        'FizzBuzz\n' +
        '16\n' +
        '17\n' +
        'Fizz\n' +
        '19\n' +
        'Buzz\n' +
        'Fizz\n' +
        '22\n' +
        '23\n' +
        'Fizz\n' +
        'Buzz\n' +
        '26\n' +
        'Fizz\n' +
        '28\n' +
        '29\n' +
        'FizzBuzz\n' +
        '31\n' +
        '32\n' +
        'Fizz\n' +
        '34\n' +
        'Buzz\n' +
        'Fizz\n' +
        '37\n' +
        '38\n' +
        'Fizz\n' +
        'Buzz\n' +
        '41\n' +
        'Fizz\n' +
        '43\n' +
        '44\n' +
        'FizzBuzz\n' +
        '46\n' +
        '47\n' +
        'Fizz\n' +
        '49\n' +
        'Buzz\n' +
        'Fizz\n' +
        '52\n' +
        '53\n' +
        'Fizz\n' +
        'Buzz\n' +
        '56\n' +
        'Fizz\n' +
        '58\n' +
        '59\n' +
        'FizzBuzz\n' +
        '61\n' +
        '62\n' +
        'Fizz\n' +
        '64\n' +
        'Buzz\n' +
        'Fizz\n' +
        '67\n' +
        '68\n' +
        'Fizz\n' +
        'Buzz\n' +
        '71\n' +
        'Fizz\n' +
        '73\n' +
        '74\n' +
        'FizzBuzz\n' +
        '76\n' +
        '77\n' +
        'Fizz\n' +
        '79\n' +
        'Buzz\n' +
        'Fizz\n' +
        '82\n' +
        '83\n' +
        'Fizz\n' +
        'Buzz\n' +
        '86\n' +
        'Fizz\n' +
        '88\n' +
        '89\n' +
        'FizzBuzz\n' +
        '91\n' +
        '92\n' +
        'Fizz\n' +
        '94\n' +
        'Buzz\n' +
        'Fizz\n' +
        '97\n' +
        '98\n' +
        'Fizz\n' +
        'Buzz\n');
});